### ISSUE TITLE
Description always enabled

### ISSUE THREAD

**Issue by lucaswerkmeister** [Ladsgroup/Vandalism-dashboard#2]
As reported by Magnus on the mailing list – “changes in descriptions” is always enabled for some reason. Apparently, the code expects `description=off` in the query string when that checkbox is off (whereas for other checkboxes is only checks if they’re present or not), but I don’t understand why the browser would send that.

**Comment by magnusmanske** [comment]
Why would you expect it to be "off"? It's either undefined (not checked, thus not added to the request) or set to some value (probably _true_) [here](https://github.com/Ladsgroup/Vandalism-dashboard/blob/master/index.php#L28).
