### ISSUE TITLE
2 Suggestions to be added

### ISSUE THREAD

**Issue by alanajjar** [Ladsgroup/Vandalism-dashboard#3]
Hello, thanks for this tool, It'll help us very much in ar.wikipedia.

I wish if you can add the number of changes that appear and that users can determine the number that will appear? (i.e. now just the last 50 changes appear, I wish I can see the last 100 or 200 or just 10).

Also can you add a rollback or undo button in a column beside ORES damaging score? 

Thanks,
Ala'a

**Comment by lucaswerkmeister** [comment]
> I wish if you can add the number of changes that appear and that users can determine the number that will appear? (i.e. now just the last 50 changes appear, I wish I can see the last 100 or 200 or just 10).

This is actually possible right now, you can add `&limit=200` to the URL and it will be used (up to 500). But we should probably add some way to control that in the UI :)

**Comment by Ladsgroup** [comment]
For rollback, I think we might need another issue.
