### ISSUE TITLE
User page links broken for those with spaces in username

### ISSUE THREAD

**Issue by mahir256** [Ladsgroup/Vandalism-dashboard#4]
Links to userpages of users with spaces in their names are broken. For example, "Tanay barisha"'s userpage becomes a link to "User:Tanay" and not "User:Tanay barisha" as expected.

**Comment by lucaswerkmeister** [comment]
Thanks! Should hopefully be fixed now :)

**Comment by lucaswerkmeister** [comment]
Though I have to admit I don’t know why it didn’t work before, a space in the URL should still work I think… can you confirm that the fix works in your case?
